### ISSUE TITLE
Messages table page

### ISSUE THREAD

**Issue by Albert221** [Arbify/Arbify#11]
### Todo
- [x] Adding messages with modal instead of new page. #9 
- [x] Dynamically shown progress of translating in the table header. 32a8dc3
- [x] Optimized page. Right now it takes 1 second for Fast Shopping. 54dd3db
- [x] Better UX of translating message values. Save after leaving the input. 32a8dc3
- [x] Sticky table header. c2543f4
- [x] Correct sizing of table columns. 2ffd35f
- [x] Dynamic deleting messages #22
